In [21]:
import numpy as np

#1

arr1d = np.arange(10)
print(arr1d)


#2

arr2d = arr1d.reshape(2, 5)
print(arr2d)

#3

arrRange = np.arange(30, 71)
print(arrRange)

#4

arrAppend = np.append(arrRange, 100)
print(arrAppend)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70 100]
